<?php
defined('IS_RUN') or exit('/**error:404**/');
/**
 * 
 */
return array(
	'godok.cn','phpstart','phpstart','《PHPSTART》','《PHPSTART》','《PHPSTART》','《PHPSTART》',
	'《PHPSTART》',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'《PHPSTART开发手册》<div>开发手册地址：<a href="http://www.kancloud.cn/fafa2088/phpstart/228415" target="_blank">http://www.kancloud.cn/fafa2088/phpstart/228415</a></div></div>',
	'路由URL清晰<div>phpstart提供的路由思路，清晰易学，路由非常接近直接访问文件</div>',
	'支持MVC模式<div>phpstart提供MVC模式开发相关函数，可轻松布局你的程序框架</div>',
	'数据库规范<div>提供pdo兼容，建议使用pdo来操作数据库</div>',
	'多级程序<div>phpstart提供多级程序的支持，程序中可以包含子程序，路由与访问子文件夹方式相同，不限制级数，子程序可调用上级程序的MVC资源</div>',
	'创新模块思路<div>phpstart把模块当子程序，每个模块可以有单独的MVC资源，模块的所有资源都在模块文件夹中，方便模块的安装和删除</div>',
	'程序资源互用<div>你可以把多个程序放置同一个项目中，程序间可以互相调用一些资源，phpstart提供便捷的调用方法。</div>',
	'高效运行<div>phpstart核心代码简洁，源码易懂，逻辑清晰，流程极简，消耗的系统资源微乎其微</div>',
	'挂载方案<div>phpstart项目可以放置在其他框架开发的站点中，URL路由与纯PHPSTART路由相同</div>',
	'下载PHPSTART<div>github地址：<a href="https://github.com/godok/phpstart" target="_blank">https://github.com/godok/phpstart</a></div><div>码市git地址：https://git.coding.net/godok/phpstart.git</div>',
	'php学完就学phpstart',
	'新手福音',
	'入口文件可修改<div>只需要在入口文件中加入 include ../phpstart/ps.php;</div>',
	'单项目多程序<div>一个站点中可包含多个程序（如cms，bbs，shop等），程序间资源可互相调用</div>',
	'自由搭配',
	'请开启rewrite来美化路由',
	'如何加载类？<div>$cat = C("cat");</div>',
	'如何加载模型？<div>$book = M("book");</div>',
	'如何加载模版？<div>include V("index");</div>',
	'如何加载函数库？<div>F("myfunc");</div>',
	'如何加载library？<div>L("lib");</div>',
	'如何获取缓存？<div>$menu = PS::getCache("menu")</div>',
	'如何写缓存？<div>PS::putCache("menu",array("home","book");</div>',
	'如何获取配置？<div>$student = PS::appConfig("student.lists");</div>',
	'L("lib")',
	'C("cat")',
	'M("book")',
	'include V("index")',
	'F("myfunc")',
	'PS::getCache("menu")',
	'PS::getCache("menu")',
	'putCache("menu","home")',
	'X(XSS注入代码)',
	'IS_RUN<div>是否运行在phpstart中</div>',
	'DOCUMENT_ROOT<div>phpstart入口文件目录，我们把他当作phpstart项目的根目录，不一定是站点根目录</div>',
	'DEFAULT_APP<div>默认程序名，test</div>',
	'APP_PATH<div>当前程序相对路径，默认是test， 可以设置成多级路径 ，如：test/app1</div>',
	'APP_ROOT<div>当前程序目录</div>',
	'SCRIPT_NAME<div>当前控制器脚本文件名</div>',
	'SCRIPT_PATH<div>当前控制器脚本文件相对地址</div>',
	'SYS_START_TIME<div>系统开始时间</div>',
	'CACHE_PATH<div>当前程序缓存文件目录</div>',
	'HTTP_HOST<div>域名</div>',
	'HTTP_REFERER<div>来源页面</div>',
	'CONTROLL<div>当前路由的控制器名称</div>',
	'ACTION<div>当前路由的行为/方法</div>',
	'DEFAULT_DB<div>默认数据库链接名，默认数据库连接名是master，DEFAULT_DB常量未定义，定义后会改变默认数据库链接名</div>',
	'$_SESSION["ip"]<div>访客IP</div>',
	'1天学会',
	'半天上手',
	'快速精通',
	'99Kb 核心',
);


?>